GET http://127.0.0.1:8000/api/generate?startDate=2024-01-01&endDate=2024-03-01&numEmployees=2
###
POST http://127.0.0.1:8000/api/generate/


{
  "metadata": {
    "start_date": "2024-01-01",
    "end_date": "2024-03-01",
    "created_at_date": "2023-11-06 12:00:49:372401",
    "employees": [
      {
        "id": 1,
        "name": "Kira Holzapfel",
        "vacation_schedule": [
          "2024-12-08",
          "2024-01-08",
          "2024-02-07",
          "2024-01-26",
          "2024-01-13"
        ]
      },
      {
        "id": 2,
        "name": "Burghard Schulz",
        "vacation_schedule": [
          "2024-12-26",
          "2024-02-21",
          "2024-02-03",
          "2024-02-14",
          "2024-02-09"
        ]
      }
    ]
  }
}
###
POST http://127.0.0.1:8000/api/stats/

{
  "metadata": {
    "start_date": "2024-01-01",
    "end_date": "2024-03-01",
    "created_at_date": "2023-11-06 12:00:49:372401",
    "employees": [
      {
        "id": 1,
        "name": "Kira Holzapfel",
        "vacation_schedule": [
          "2024-12-08",
          "2024-01-08",
          "2024-02-07",
          "2024-01-26",
          "2024-01-13"
        ]
      },
      {
        "id": 2,
        "name": "Burghard Schulz",
        "vacation_schedule": [
          "2024-12-26",
          "2024-02-21",
          "2024-02-03",
          "2024-02-14",
          "2024-02-09"
        ]
      }
    ],
    "algorithm_execution_time_ms": 13812.75
  },
  "schedule": [
    1,
    1,
    1,
    1,
    1,
    2,
    2,
    2,
    1,
    2,
    2,
    1,
    2,
    2,
    2,
    2,
    2,
    2,
    1,
    2,
    2,
    2,
    1,
    1,
    1,
    2,
    1,
    1,
    2,
    2,
    2,
    2,
    2,
    1,
    2,
    2,
    2,
    2,
    1,
    1,
    1,
    2,
    1,
    2,
    1,
    1,
    1,
    1,
    1,
    2,
    2,
    1,
    2,
    1,
    1,
    1,
    1,
    1,
    1,
    2
  ]
}